MAIL_USER: ""       # 邮件用户名
MAIL_PASS: ""       # 邮件密码
GITLAB_TOKEN: ''    # TOKEN 非常重要
GITLAB_BASE_URL: 'http://gitlab.dxy.net'
GITLAB_PROJECT_ID: 86           # project id ，可以通过抓包获得，也可以走api，如果有权限的话
VS_MAIL_FROM : ''               # 发送人
VS_MAIL_TO:  'mzhang@dxy.cn'    # 邮件接收人
VS_PUBLISH_MANAGER: 'manager'   # 管理员称呼
VS_GITLAB_BRANCH: 'master'      # 默认分支
VS_MAIL_CC: ['']                # cc列表


BAIDU_API_KEY: ''  #百度api key
BAIDU_API_URL: 'http://apis.baidu.com/apistore/weatherservice/citylist'
BAIDU_TURING_URL: 'http://apis.baidu.com/turing/turing/turing'
BAIDU_TURING_KEY: '' #图灵机器人key
